spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employee_management?serverTimezone=America/Edmonton
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      password: 123456